### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Lmmb74** [ParaPenguin/SporkPGM#72]
When I try to compile the snapshot, the console gies me this error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project spork: Compilation failure
[ERROR] /C:/Users/Lautaro/Desktop/SporkPGM-master/src/main/java/in/parapengu/spo
rk/module/modules/kit/KitModule.java:[6,1] annotation @in.parapengu.spork.module
.builder.ModuleBuilder is missing a default value for the element 'value'

What do I have to do?

**Comment by TheMolkaPL** [comment]
You must fix this annotation.

**Comment by Lmmb74** [comment]
How do I do that?

**Comment by kblanks** [comment]
Please wait for the next version of Spork.
